### PR TITLE
Fixes a bug where pawns can jump over pieces

### PR DESCRIPTION
**Pull request by Kinrany**
white pawn can jump over black pawn

### CODE REVIEW

**Review by jvanbruegge — APPROVED** [review]

**Comment by jvanbruegge** [comment]
Thanks!

**Comment by Kinrany** [comment]
😄 
Note that I didn't change `/docs`, so the demo on the static site still has the bug.
Also, is `npm run start` supposed to work?

**Comment by jvanbruegge** [comment]
Yeah, I will republish the hosted demo.

`npm start` should work, maybe because I set the `publicPath` to `./` in `webpack.config.js`? It was working before that and I havent tested afterwards

**Comment by Kinrany** [comment]
Yep, it works if I remove `publicPath` or replace it with `/`, not sure why.

**Pull request merged**
